# Generated by Django 2.2.1 on 2019-06-21 05:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(blank=True, max_length=30, unique=True)),
                ('role', models.CharField(blank=True, max_length=20)),
                ('phone_number', models.CharField(max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('remarks', models.CharField(max_length=300, null=True)),
                ('status', models.IntegerField(default=1)),
                ('published_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit_commission', models.FloatField()),
                ('auction_commission', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('remarks', models.CharField(max_length=300, null=True)),
                ('status', models.IntegerField(default=1)),
                ('published_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('remarks', models.CharField(max_length=300, null=True)),
                ('start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.IntegerField(default=1)),
                ('published_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('chit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chit.Chit')),
            ],
        ),
        migrations.CreateModel(
            name='GroupAuction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('auction_amount', models.IntegerField(default=0)),
                ('payable', models.IntegerField(default=0)),
                ('month', models.IntegerField(default=0)),
                ('remarks', models.CharField(blank=True, max_length=300, null=True)),
                ('published_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('status', models.IntegerField(default=0)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chit.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=10, null=True)),
                ('note', models.CharField(max_length=300, null=True)),
                ('status', models.IntegerField(default=1)),
                ('published_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='', max_length=10)),
                ('status', models.IntegerField(default=1)),
                ('published_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('amount', models.IntegerField()),
                ('remarks', models.CharField(blank=True, max_length=300, null=True)),
                ('payment_mode', models.CharField(max_length=50)),
                ('published_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chit.Members')),
            ],
        ),
        migrations.CreateModel(
            name='PayableAuction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_payable', models.IntegerField(default=0)),
                ('paid_amount', models.IntegerField(default=0)),
                ('payment_status', models.IntegerField(default=0)),
                ('updated_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('auction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chit.GroupAuction')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chit.Group')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chit.Members')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chit.Group')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chit.Members')),
            ],
        ),
        migrations.AddField(
            model_name='groupauction',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chit.Members'),
        ),
        migrations.AddField(
            model_name='group',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chit.Type'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('amount', models.IntegerField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chit.ExpenseCategory')),
            ],
        ),
    ]
