# Generated by Django 2.2.1 on 2019-06-21 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outstanding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chit.Group')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chit.Members')),
            ],
        ),
    ]
