# Generated by Django 2.2.1 on 2019-06-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chit', '0002_outstanding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outstanding',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='outstanding',
            old_name='member_id',
            new_name='member',
        ),
        migrations.AlterField(
            model_name='outstanding',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
