# Generated by Django 2.2.1 on 2019-06-21 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chit', '0003_auto_20190621_1613'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Outstanding',
        ),
    ]
